#!/usr/bin/env python3
"""Extract the string-id tables from src/battle_message.c into sim/gen/string_tables.c + a header."""
import re, sys, os
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
src = open(os.path.join(root, 'src/battle_message.c')).read()
out = ['// Generated by sim/tools/extract_tables.py -- string id tables from src/battle_message.c',
       '#include "global.h"', '#include "battle.h"', '#include "battle_message.h"', '#include "battle_controllers.h"',
       '#include "constants/battle_string_ids.h"', '#include "constants/moves.h"', '#include "constants/weather.h"', '']
names = []
for m in re.finditer(r'^const u16 (g\w+)\[[^\]]*\] =\s*\n\{', src, re.M):
    start = m.start(); i = m.end(); depth = 1
    while depth:
        c = src[i]
        if c == '{': depth += 1
        elif c == '}': depth -= 1
        i += 1
    while src[i] != ';': i += 1
    out.append(src[start:i+1]); out.append('')
    names.append(m.group(1))
open(sys.argv[1], 'w').write('\n'.join(out))
with open(sys.argv[2], 'w') as f:
    f.write('// Generated by sim/tools/extract_tables.py\n#ifndef GUARD_SIM_STRING_TABLES_H\n#define GUARD_SIM_STRING_TABLES_H\n#include "global.h"\n')
    for n in names:
        f.write('extern const u16 %s[];\n' % n)
    f.write('#endif\n')
print(len(names), 'tables')
