#!/usr/bin/env python3
"""Generate tests/scenarios/type_matrix.c: one 100%-accuracy move of every attacking type against a
defender of every type (single-typed where the generation has one), asserting the effectiveness message
from an independent Gen 3 type chart. Cross-checked against the ROM as well."""
import sys
# attacking type -> (move, user)
ATTACKS = [
    ('NORMAL',   'MOVE_TACKLE'),      ('FIGHTING', 'MOVE_KARATE_CHOP'), ('FLYING', 'MOVE_WING_ATTACK'),
    ('POISON',   'MOVE_POISON_STING'),('GROUND',   'MOVE_EARTHQUAKE'),  ('ROCK',   'MOVE_ANCIENT_POWER'),
    ('BUG',      'MOVE_SILVER_WIND'), ('GHOST',    'MOVE_SHADOW_BALL'), ('STEEL',  'MOVE_METAL_CLAW'),
    ('FIRE',     'MOVE_EMBER'),       ('WATER',    'MOVE_WATER_GUN'),   ('GRASS',  'MOVE_VINE_WHIP'),
    ('ELECTRIC', 'MOVE_THUNDERBOLT'), ('PSYCHIC',  'MOVE_CONFUSION'),   ('ICE',    'MOVE_ICE_BEAM'),
    ('DRAGON',   'MOVE_DRAGON_CLAW'), ('DARK',     'MOVE_BITE'),
]
# defending type -> species (types)
DEFENDERS = [
    ('NORMAL', 'SPECIES_RATTATA', ['NORMAL']), ('FIGHTING', 'SPECIES_MACHOP', ['FIGHTING']),
    ('FLYING', 'SPECIES_PIDGEY', ['NORMAL', 'FLYING']), ('POISON', 'SPECIES_EKANS', ['POISON']),
    ('GROUND', 'SPECIES_SANDSHREW', ['GROUND']), ('ROCK', 'SPECIES_NOSEPASS', ['ROCK']),
    ('BUG', 'SPECIES_CATERPIE', ['BUG']), ('GHOST', 'SPECIES_SHUPPET', ['GHOST']),
    ('STEEL', 'SPECIES_MAWILE', ['STEEL']), ('FIRE', 'SPECIES_CHARMANDER', ['FIRE']),
    ('WATER', 'SPECIES_SQUIRTLE', ['WATER']), ('GRASS', 'SPECIES_TANGELA', ['GRASS']),
    ('ELECTRIC', 'SPECIES_PIKACHU', ['ELECTRIC']), ('PSYCHIC', 'SPECIES_ABRA', ['PSYCHIC']),
    ('ICE', 'SPECIES_GLALIE', ['ICE']), ('DRAGON', 'SPECIES_DRATINI', ['DRAGON']), ('DARK', 'SPECIES_ABSOL', ['DARK']),
    ('ROCK_GROUND', 'SPECIES_GEODUDE', ['ROCK', 'GROUND']), ('WATER_GROUND', 'SPECIES_QUAGSIRE', ['WATER', 'GROUND']),
    ('STEEL_PSYCHIC', 'SPECIES_METANG', ['STEEL', 'PSYCHIC']), ('GHOST_POISON', 'SPECIES_GASTLY', ['GHOST', 'POISON']),
]
# Gen 3 chart: (atk, def) -> multiplier x10; missing = 10
CHART = {}
def s(a, ds, m):
    for d in ds: CHART[(a, d)] = m
s('NORMAL', ['ROCK', 'STEEL'], 5); s('NORMAL', ['GHOST'], 0)
s('FIRE', ['FIRE', 'WATER', 'ROCK', 'DRAGON'], 5); s('FIRE', ['GRASS', 'ICE', 'BUG', 'STEEL'], 20)
s('WATER', ['WATER', 'GRASS', 'DRAGON'], 5); s('WATER', ['FIRE', 'GROUND', 'ROCK'], 20)
s('ELECTRIC', ['ELECTRIC', 'GRASS', 'DRAGON'], 5); s('ELECTRIC', ['WATER', 'FLYING'], 20); s('ELECTRIC', ['GROUND'], 0)
s('GRASS', ['FIRE', 'GRASS', 'POISON', 'FLYING', 'BUG', 'DRAGON', 'STEEL'], 5); s('GRASS', ['WATER', 'GROUND', 'ROCK'], 20)
s('ICE', ['WATER', 'ICE', 'FIRE', 'STEEL'], 5); s('ICE', ['GRASS', 'GROUND', 'FLYING', 'DRAGON'], 20)
s('FIGHTING', ['POISON', 'FLYING', 'PSYCHIC', 'BUG'], 5); s('FIGHTING', ['NORMAL', 'ICE', 'ROCK', 'DARK', 'STEEL'], 20); s('FIGHTING', ['GHOST'], 0)
s('POISON', ['POISON', 'GROUND', 'ROCK', 'GHOST'], 5); s('POISON', ['GRASS'], 20); s('POISON', ['STEEL'], 0)
s('GROUND', ['GRASS', 'BUG'], 5); s('GROUND', ['FIRE', 'ELECTRIC', 'POISON', 'ROCK', 'STEEL'], 20); s('GROUND', ['FLYING'], 0)
s('FLYING', ['ELECTRIC', 'ROCK', 'STEEL'], 5); s('FLYING', ['GRASS', 'FIGHTING', 'BUG'], 20)
s('PSYCHIC', ['PSYCHIC', 'STEEL'], 5); s('PSYCHIC', ['FIGHTING', 'POISON'], 20); s('PSYCHIC', ['DARK'], 0)
s('BUG', ['FIRE', 'FIGHTING', 'POISON', 'FLYING', 'GHOST', 'STEEL'], 5); s('BUG', ['GRASS', 'PSYCHIC', 'DARK'], 20)
s('ROCK', ['FIGHTING', 'GROUND', 'STEEL'], 5); s('ROCK', ['FIRE', 'ICE', 'FLYING', 'BUG'], 20)
s('GHOST', ['DARK', 'STEEL'], 5); s('GHOST', ['PSYCHIC', 'GHOST'], 20); s('GHOST', ['NORMAL'], 0)
s('DRAGON', ['STEEL'], 5); s('DRAGON', ['DRAGON'], 20)
s('DARK', ['FIGHTING', 'DARK', 'STEEL'], 5); s('DARK', ['PSYCHIC', 'GHOST'], 20)
s('STEEL', ['FIRE', 'WATER', 'ELECTRIC', 'STEEL'], 5); s('STEEL', ['ICE', 'ROCK'], 20)

out = ['// Generated by sim/tools/gen_type_matrix.py -- do not edit', '#include "scenario.h"', '',
'''static void ExpectClass(struct BattleSim *sim, int cls)
{
    int hit = LOG_INDEX_T(STRINGID_USEDMOVE, 0, 0) >= 0 && !LOG_HAS(STRINGID_ATTACKMISSED);
    if (!hit) return; // Metal Claw can miss; the ROM cross-check still compares state
    if (cls == 0)
        CHECK(HP(1) == MAXHP(1) && (LOG_HAS(STRINGID_ITDOESNTAFFECT) || LOG_HAS(STRINGID_PKMNMAKESGROUNDMISS)), "immune");
    else if (cls == 1)
        CHECK(HP(1) < MAXHP(1) && LOG_HAS(STRINGID_NOTVERYEFFECTIVE) && !LOG_HAS(STRINGID_SUPEREFFECTIVE), "not very effective");
    else if (cls == 2)
        CHECK(HP(1) < MAXHP(1) && !LOG_HAS(STRINGID_NOTVERYEFFECTIVE) && !LOG_HAS(STRINGID_SUPEREFFECTIVE) && !LOG_HAS(STRINGID_ITDOESNTAFFECT), "neutral");
    else
        CHECK(HP(1) < MAXHP(1) && LOG_HAS(STRINGID_SUPEREFFECTIVE) && !LOG_HAS(STRINGID_NOTVERYEFFECTIVE), "super effective");
}
static void CheckImmune(struct BattleSim *sim) { ExpectClass(sim, 0); }
static void CheckResisted(struct BattleSim *sim) { ExpectClass(sim, 1); }
static void CheckNeutral(struct BattleSim *sim) { ExpectClass(sim, 2); }
static void CheckSuper(struct BattleSim *sim) { ExpectClass(sim, 3); }
''', 'static const struct Scenario sScenarios[] =', '{']
n = 0
for atk, move in ATTACKS:
    for dname, species, types in DEFENDERS:
        mult = 100
        for t in types:
            mult = mult * CHART.get((atk, t), 10) // 10
        if atk == 'GROUND' and species == 'SPECIES_GASTLY':
            mult = 0  # Levitate
        cls = 0 if mult == 0 else 1 if mult < 100 else 2 if mult == 100 else 3
        check = ['CheckImmune', 'CheckResisted', 'CheckNeutral', 'CheckSuper'][cls]
        out.append('    { .name = "%s_vs_%s", .player = { MON(SPECIES_SMEARGLE, 50, %s, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH) },'
                   % (atk.lower(), dname.lower(), move))
        out.append('      .enemy = { MON(%s, 50, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH) }, .actions = { T(0, 0) }, .turns = 1, .check = %s },' % (species, check))
        n += 1
out += ['};', '', 'SCENARIO_GROUP(type_matrix, sScenarios)', '']
open(sys.argv[1], 'w').write('\n'.join(out))
print(n, 'type matrix scenarios')
