#!/usr/bin/env python3
"""Generate tests/scenarios/coverage.c: one scenario per thinly covered move and ability.

Thin = used fewer than MOVE_MIN times / seen fewer than ABILITY_MIN times in the recorded ROM corpus
(tools/coverage.py corpus). For each such move the lowest-id natural user (not Smeargle) at level 100 uses it
for three turns against a Splash Snorlax; for each ability a bearer sits through two turns. These scenarios have
no checks of their own; their value is the ROM cross-check and the recorded transcript.

  python3 tools/gen_coverage_scenarios.py [--move-min N] [--ability-min N]
"""
import collections, os, re, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import coverage as C
import teams as T

ROOT = C.ROOT
MOVE_MIN = 6
ABILITY_MIN = 70

# moves whose normal use needs a setup the plain scenario cannot give; still generated (they fail visibly in
# the ROM too, which is a valid comparison) but a note marks them
NEEDS_SETUP = {'SKETCH', 'SNORE', 'SLEEP_TALK', 'SPIT_UP', 'SWALLOW', 'COUNTER', 'MIRROR_COAT', 'BIDE', 'DREAM_EATER',
               'NIGHTMARE', 'FOCUS_PUNCH', 'ENDEAVOR', 'MAGIC_COAT', 'SNATCH', 'FAKE_OUT'}


def main():
    args = sys.argv[1:]
    move_min, ability_min = MOVE_MIN, ABILITY_MIN
    if '--move-min' in args: move_min = int(args[args.index('--move-min') + 1])
    if '--ability-min' in args: ability_min = int(args[args.index('--ability-min') + 1])

    t, inv = C.tables()
    # corpus counters (same decoding as coverage.py corpus)
    import glob, gzip
    used, ab = collections.Counter(), collections.Counter()
    prev = {}
    for path in sorted(glob.glob(os.path.join(ROOT, 'corpus', '*.trace*'))):
        for line in C.read_trace(path):
            if line.startswith('START '):
                prev = {}
            elif line.startswith('MONS '):
                raw = bytes.fromhex(line[5:])
                for b in range(4):
                    m = raw[b * 88:(b + 1) * 88]
                    species = m[0] | (m[1] << 8)
                    if species == 0 or species >= C.NUM_SPECIES: continue
                    moves = [m[12 + 2 * i] | (m[13 + 2 * i] << 8) for i in range(4)]
                    pp = list(m[36:40])
                    ab[m[32]] += 1
                    p = prev.get(b)
                    if p and p[0] == species:
                        for i in range(4):
                            if moves[i] and p[1][i] == moves[i] and pp[i] < p[2][i]:
                                used[moves[i]] += 1
                    prev[b] = (species, moves, pp)
    thin_moves = [mv for mv in range(1, len(inv['moves'])) if mv != C.STRUGGLE and used.get(mv, 0) < move_min]
    thin_abils = [a for a in range(1, len(inv['abilities'])) if 0 < ab.get(a, 0) < ability_min or ab.get(a, 0) == 0]

    # legal users at level 100 (skip Smeargle: it can learn everything)
    exe = os.path.join(ROOT, 'build', 'teamcheck')
    learn = {}
    for sp in C.REAL_SPECIES:
        name = inv['species'][sp]
        if name == 'SMEARGLE': continue
        out = subprocess.run([exe, '--moves', name, '100'], capture_output=True, text=True).stdout.split()
        learn[sp] = set(t['moves'][x] for x in out if x in t['moves'])
    spab = C.species_abilities()

    lines = ['// Generated by sim/tools/gen_coverage_scenarios.py -- do not edit',
             '// One scenario per move/ability that the recorded ROM corpus exercised fewer than %d/%d times.' % (move_min, ability_min),
             '#include "scenario.h"', '',
             '#define SNORLAX100 MON(SPECIES_SNORLAX, 100, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH)', '',
             'static const struct Scenario sScenarios[] =', '{']
    n_moves = 0
    for mv in thin_moves:
        mname = inv['moves'][mv]
        users = [sp for sp in C.REAL_SPECIES if sp in learn and mv in learn[sp]]
        if not users:
            lines.append('    // %s: no natural user' % mname)
            continue
        sp = users[0]
        sname = inv['species'][sp]
        fate = ', .fateful = 1' if sname in ('MEW', 'DEOXYS') else ''
        note = '  // needs a setup this scenario does not give' if mname in NEEDS_SETUP else ''
        lines.append('    { .name = "move_%s", .player = { { .species = SPECIES_%s, .level = 100, .moves = { MOVE_%s, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH }%s } },'
                     % (mname.lower(), sname, mname, fate))
        lines.append('      .enemy = { SNORLAX100 }, .actions = { T(0, 0), T(0, 0), T(0, 0) }, .turns = 3 },%s' % note)
        n_moves += 1
    n_ab = 0
    for a in thin_abils:
        aname = inv['abilities'][a]
        bearers = [sp for sp in C.REAL_SPECIES if a in spab.get(sp, set())]
        if not bearers:
            lines.append('    // %s: no bearer' % aname)
            continue
        sp = bearers[0]
        slot = 1 if sorted(spab[sp])[0] != a and len(spab[sp]) > 1 else 0
        sname = inv['species'][sp]
        atk = 'MOVE_TACKLE' if t['moves']['TACKLE'] in learn.get(sp, set()) else 'MOVE_SPLASH'
        lines.append('    { .name = "ability_%s", .player = { MON_AB(SPECIES_%s, 100, %s, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH, %d) },'
                     % (aname.lower(), sname, atk, slot))
        lines.append('      .enemy = { MON(SPECIES_RATTATA, 100, MOVE_TACKLE, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH) }, .actions = { T(0, 0), T(0, 0) }, .turns = 2 },')
        n_ab += 1
    lines += ['};', '', 'SCENARIO_GROUP(coverage, sScenarios)', '']
    open(os.path.join(ROOT, 'tests', 'scenarios', 'coverage.c'), 'w').write('\n'.join(lines))
    print('coverage.c: %d move scenarios, %d ability scenarios' % (n_moves, n_ab))


if __name__ == '__main__':
    main()
