#!/usr/bin/env python3
"""Generate a compact item table (hold effects, pockets, battle usage, names) from src/data/items.json."""
import json, os, sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
items = json.load(open(os.path.join(root, 'src/data/items.json')))['items']
with open(sys.argv[1], 'w') as f:
    f.write('// Generated by sim/tools/gen_items.py from src/data/items.json -- do not edit\n')
    f.write('#include "global.h"\n#include "item.h"\n#include "sim_items.h"\n#include "constants/items.h"\n#include "constants/hold_effects.h"\n#include "constants/global.h"\n\n')
    f.write('const struct SimItem gSimItems[ITEMS_COUNT] = {\n')
    for it in items:
        name = it['english'].replace('\\', '\\\\').replace('"', '\\"')
        f.write('    [%s] = { .holdEffect = %s, .holdEffectParam = %d, .pocket = %s, .battleUsage = %d, .price = %d, .name = "%s" },\n' % (
            it['itemId'], it['holdEffect'], it['holdEffectParam'], it['pocket'], it['battleUsage'], it['price'], name))
    f.write('};\n')
print(len(items), 'items')
