#!/usr/bin/env python3
"""Generate ASCII name tables (moves, species, abilities, battle string ids) from the constants headers."""
import os, re, sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

def defines(path, prefix):
    out = {}
    for line in open(os.path.join(root, path)):
        m = re.match(r'#define\s+(%s\w+)\s+(\S+)' % prefix, line)
        if m:
            try:
                out[int(m.group(2), 0)] = m.group(1)
            except ValueError:
                pass
    return out

def emit(f, name, table, count_expr):
    f.write('const char *const %s[] = {\n' % name)
    n = max(table) + 1
    for i in range(n):
        f.write('    "%s",\n' % table.get(i, '?'))
    f.write('};\nconst int %s_Count = %d;\n' % (name, n))

with open(sys.argv[1], 'w') as f:
    f.write('// Generated by sim/tools/gen_names.py -- do not edit\n#include "sim_names.h"\n')
    emit(f, 'gSimMoveNames', {k: v[5:] for k, v in defines('include/constants/moves.h', 'MOVE_').items() if v != 'MOVES_COUNT'}, 'MOVES_COUNT')
    emit(f, 'gSimSpeciesNames', {k: v[8:] for k, v in defines('include/constants/species.h', 'SPECIES_').items() if not v.startswith('SPECIES_OLD_UNOWN') and v != 'SPECIES_EGG'}, 'NUM_SPECIES')
    emit(f, 'gSimAbilityNames', {k: v[8:] for k, v in defines('include/constants/abilities.h', 'ABILITY_').items()}, 'ABILITIES_COUNT')
    emit(f, 'gSimStringIdNames', {k: v[9:] for k, v in defines('include/constants/battle_string_ids.h', 'STRINGID_').items()}, 'BATTLESTRINGS_COUNT')
    emit(f, 'gSimItemNames', {k: v[5:] for k, v in defines('include/constants/items.h', 'ITEM_').items() if v not in ('ITEMS_COUNT',)}, 'ITEMS_COUNT')
print('ok')
