#!/usr/bin/env python3
"""Read the harness ROM's linker map and emit the addresses the Lua bridge and the host driver need:
   gen_harness_addrs.py pokefirered_modern_harness.map harness/harness.lua harness/harness_gen.lua gen/harness_addrs.h"""
import re, sys

SYMBOLS = ['gSimHarness', 'gBattleMons', 'gStatuses3', 'gSideStatuses', 'gSideTimers', 'gDisableStructs',
           'gBattleWeather', 'gWishFutureKnock', 'gPlayerParty', 'gEnemyParty', 'gBattlerPartyIndexes',
           'gAbsentBattlerFlags', 'gBattleOutcome', 'gBattleResults', 'gProtectStructs', 'gRngValue',
           'gBattlersCount', 'gBattleTypeFlags', 'gBattleCommunication', 'gBattleControllerExecFlags', 'gSimHarnessShadow']
# Objects whose Random() calls the simulator also makes (everything else is UI/animation noise).
# Functions inside engine objects whose Random() calls are frame-driven (not made by the simulator).
EXCLUDE_FUNCS = ['VBlankCB_Battle']
ENGINE_OBJECTS = ['battle_main.o', 'battle_util.o', 'battle_script_commands.o', 'pokemon.o',
                  'battle_ai_script_commands.o', 'battle_ai_switch_items.o', 'battle_controller_opponent.o',
                  'battle_controllers.o', 'battle_controller_player.o', 'sim_harness.o']

def main():
    mapfile, template, out_lua, out_h = sys.argv[1:5]
    addrs = {}
    ranges = []
    cur_obj_text = None
    for line in open(mapfile):
        m = re.match(r'\s+0x([0-9a-f]{8})\s+(\w+)\s*(= \.)?\s*$', line)
        if m and m.group(2) in SYMBOLS and m.group(2) not in addrs:
            addrs[m.group(2)] = int(m.group(1), 16)
        # ".text  0x08xxxxxx  0xSIZE build/.../src/foo.o"
        m = re.match(r'\s+\.text\s+0x([0-9a-f]{8})\s+0x([0-9a-f]+)\s+(?:\S*/)?src/(\w+\.o)\s*$', line)
        if m and m.group(3) in ENGINE_OBJECTS:
            ranges.append((m.group(3), int(m.group(1), 16), int(m.group(1), 16) + int(m.group(2), 16)))
    # exclusion ranges: from the function's address to the next symbol listed in the map
    syms = []
    for line in open(mapfile):
        m = re.match(r'\s+0x(08[0-9a-f]{6})\s+(\w+)\s*$', line)
        if m:
            syms.append((int(m.group(1), 16), m.group(2)))
    syms.sort()
    excludes = []
    for i, (a, n) in enumerate(syms):
        if n in EXCLUDE_FUNCS:
            nxt = next((b for b, _ in syms[i + 1:] if b > a), a + 0x100)
            excludes.append((n, a, nxt))
    missing = [s for s in SYMBOLS if s not in addrs]
    if missing:
        raise SystemExit('symbols not found in map: ' + ' '.join(missing))
    if len(ranges) < 8:
        raise SystemExit('engine .text ranges not found (got %d)' % len(ranges))
    # engine ranges with the excluded functions cut out
    eng = []
    for name, a, b in ranges:
        pieces = [(a, b)]
        for _, xa, xb in excludes:
            out = []
            for (pa, pb) in pieces:
                if xb <= pa or xa >= pb:
                    out.append((pa, pb))
                else:
                    if pa < xa: out.append((pa, xa))
                    if xb < pb: out.append((xb, pb))
            pieces = out
        eng.extend(pieces)
    with open(out_lua, 'w') as f:
        f.write('-- Generated by sim/tools/gen_harness_addrs.py from %s -- do not edit\n' % mapfile)
        f.write('A = {\n')
        for k, v in addrs.items():
            f.write('  %s = 0x%08x,\n' % (k, v))
        f.write('}\n')
        f.write('ENGINE_RANGES = {\n')
        for a, b in eng:
            f.write('  {0x%08x, 0x%08x},\n' % (a, b))
        f.write('}\n\n')
        f.write(open(template).read())
    with open(out_h, 'w') as f:
        f.write('// Generated by sim/tools/gen_harness_addrs.py -- do not edit\n')
        for k, v in addrs.items():
            f.write('#define HARNESS_ADDR_%s 0x%08xu\n' % (k, v))
        f.write('static const struct { const char *name; unsigned start, end; } sHarnessEngineRanges[] = {\n')
        for name, a, b in ranges:
            f.write('    { "%s", 0x%08xu, 0x%08xu },\n' % (name, a, b))
        f.write('};\n')
        f.write('static const struct { unsigned addr; const char *name; } sHarnessSymbols[] = {\n')
        for a, n in syms:
            if any(r[1] <= a < r[2] for r in ranges):
                f.write('    { 0x%08xu, "%s" },\n' % (a, n))
        f.write('};\n')
        f.write('static const struct { const char *name; unsigned start, end; } sHarnessExcludeRanges[] = {\n')
        for name, a, b in excludes:
            f.write('    { "%s", 0x%08xu, 0x%08xu },\n' % (name, a, b))
        f.write('};\n')
    print('excluded:', ', '.join('%s[%08x-%08x]' % r for r in excludes))
    print('addresses:', ', '.join('%s=%08x' % kv for kv in addrs.items()))
    print('engine ranges:', ', '.join('%s[%08x-%08x]' % r for r in ranges))

if __name__ == '__main__':
    main()
