#!/usr/bin/env python3
"""Extract height/weight per national dex number from src/data/pokemon/pokedex_entries.h."""
import re, os, sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
src = open(os.path.join(root, 'src/data/pokemon/pokedex_entries.h')).read()
entries = re.findall(r'\[(NATIONAL_DEX_\w+)\]\s*=\s*\{(.*?)\n    \}', src, re.S)
with open(sys.argv[1], 'w') as f:
    f.write('// Generated by sim/tools/gen_pokedex.py from src/data/pokemon/pokedex_entries.h -- do not edit\n')
    f.write('#include "global.h"\n#include "constants/pokedex.h"\n')
    f.write('const u16 gSimPokedexHeights[] = {\n')
    for name, body in entries:
        h = re.search(r'\.height\s*=\s*(\d+)', body).group(1)
        f.write('    [%s] = %s,\n' % (name, h))
    f.write('};\nconst u16 gSimPokedexWeights[] = {\n')
    for name, body in entries:
        w = re.search(r'\.weight\s*=\s*(\d+)', body).group(1)
        f.write('    [%s] = %s,\n' % (name, w))
    f.write('};\n')
print(len(entries), 'dex entries')
