#!/usr/bin/env python3
"""Generate sim/gen/sim_state_fields.h (struct members) and sim/gen/sim_globals.h (#define remaps)
from the single list of game globals below, so the ported engine code can stay textually identical."""
import re, os, sys

FIELDS = r'''
// --- RNG ---
u32 gRngValue;
// --- battle_main.c ---
u8 gBattleTextBuff1[TEXT_BUFF_ARRAY_COUNT];
u8 gBattleTextBuff2[TEXT_BUFF_ARRAY_COUNT];
u8 gBattleTextBuff3[TEXT_BUFF_ARRAY_COUNT];
u32 gBattleTypeFlags;
u8 gBattleTerrain;
u32 gUnusedFirstBattleVar1;
struct MultiBattlePokemonTx gMultiPartnerParty[3];
u8 gBattleBufferA[MAX_BATTLERS_COUNT][0x200];
u8 gBattleBufferB[MAX_BATTLERS_COUNT][0x200];
u8 gActiveBattler;
u32 gBattleControllerExecFlags;
u8 gBattlersCount;
u16 gBattlerPartyIndexes[MAX_BATTLERS_COUNT];
u8 gBattlerPositions[MAX_BATTLERS_COUNT];
u8 gActionsByTurnOrder[MAX_BATTLERS_COUNT];
u8 gBattlerByTurnOrder[MAX_BATTLERS_COUNT];
u8 gCurrentTurnActionNumber;
u8 gCurrentActionFuncId;
struct BattlePokemon gBattleMons[MAX_BATTLERS_COUNT];
u8 gBattlerSpriteIds[MAX_BATTLERS_COUNT];
u8 gCurrMovePos;
u8 gChosenMovePos;
u16 gCurrentMove;
u16 gChosenMove;
u16 gCalledMove;
s32 gBattleMoveDamage;
s32 gHpDealt;
s32 gTakenDmg[MAX_BATTLERS_COUNT];
u16 gLastUsedItem;
u8 gLastUsedAbility;
u8 gBattlerAttacker;
u8 gBattlerTarget;
u8 gBattlerFainted;
u8 gEffectBattler;
u8 gPotentialItemEffectBattler;
u8 gAbsentBattlerFlags;
u8 gCritMultiplier;
u8 gMultiHitCounter;
const u8 *gBattlescriptCurrInstr;
u32 gUnusedBattleMainVar;
u8 gChosenActionByBattler[MAX_BATTLERS_COUNT];
const u8 *gSelectionBattleScripts[MAX_BATTLERS_COUNT];
u16 gLastPrintedMoves[MAX_BATTLERS_COUNT];
u16 gLastMoves[MAX_BATTLERS_COUNT];
u16 gLastLandedMoves[MAX_BATTLERS_COUNT];
u16 gLastHitByType[MAX_BATTLERS_COUNT];
u16 gLastResultingMoves[MAX_BATTLERS_COUNT];
u16 gLockedMoves[MAX_BATTLERS_COUNT];
u8 gLastHitBy[MAX_BATTLERS_COUNT];
u16 gChosenMoveByBattler[MAX_BATTLERS_COUNT];
u8 gMoveResultFlags;
u32 gHitMarker;
u8 sUnusedBattlersArray[MAX_BATTLERS_COUNT];
u8 gTakenDmgByBattler[MAX_BATTLERS_COUNT];
u8 gUnusedFirstBattleVar2;
u16 gSideStatuses[2];
struct SideTimer gSideTimers[2];
u32 gStatuses3[MAX_BATTLERS_COUNT];
struct DisableStruct gDisableStructs[MAX_BATTLERS_COUNT];
u16 gPauseCounterBattle;
u16 gPaydayMoney;
u16 gRandomTurnNumber;
u8 gBattleCommunication[BATTLE_COMMUNICATION_ENTRIES_COUNT];
u8 gBattleOutcome;
struct ProtectStruct gProtectStructs[MAX_BATTLERS_COUNT];
struct SpecialStatus gSpecialStatuses[MAX_BATTLERS_COUNT];
u16 gBattleWeather;
struct WishFutureKnock gWishFutureKnock;
u16 gIntroSlideFlags;
u8 gSentPokesToOpponent[2];
u16 gDynamicBasePower;
u16 gExpShareExp;
struct BattleEnigmaBerry gEnigmaBerries[MAX_BATTLERS_COUNT];
struct BattleScripting gBattleScripting;
struct BattleStruct sBattleStructStorage;
struct SimBattleResources sBattleResourcesStorage;
u8 gActionSelectionCursor[MAX_BATTLERS_COUNT];
u8 gMoveSelectionCursor[MAX_BATTLERS_COUNT];
u8 gBattlerStatusSummaryTaskId[MAX_BATTLERS_COUNT];
u8 gBattlerInMenuId;
bool8 gDoingBattleAnim;
u32 gTransformedPersonalities[MAX_BATTLERS_COUNT];
u16 gBattleMovePower;
u16 gMoveToLearn;
u8 gBattleMonForms[MAX_BATTLERS_COUNT];
void (*gBattleMainFunc)(void);
struct BattleResults gBattleResults;
u8 gLeveledUpInBattle;
void (*gBattlerControllerFuncs[MAX_BATTLERS_COUNT])(void);
u8 gHealthboxSpriteIds[MAX_BATTLERS_COUNT];
u8 gMultiUsePlayerCursor;
u8 gNumberOfMovesToChoose;
u8 gBattleControllerData[MAX_BATTLERS_COUNT];
// --- pokemon.c ---
u8 gPlayerPartyCount;
u8 gEnemyPartyCount;
struct Pokemon gEnemyParty[PARTY_SIZE];
struct Pokemon gPlayerParty[PARTY_SIZE];
// --- battle_controllers.c ---
u8 sBattleBuffersTransferData[0x100];
// --- battle_ai_script_commands.c ---
const u8 *sAIScriptPtr;
// --- other files ---
u16 gTrainerBattleOpponent_A;
u8 gBattlePartyCurrentOrder[3];
u16 gNumSafariBalls;
u16 gSpecialVar_ItemId;
u16 gLastUsedItemInBattle;
'''

def main():
    outdir = sys.argv[1]
    members, macros = [], []
    for line in FIELDS.strip().split('\n'):
        line = line.strip()
        if not line or line.startswith('//'):
            members.append(line)
            continue
        m = re.match(r'^(.*?)\b([gs][A-Z]\w*)\b(.*);$', line)
        if not m:
            raise SystemExit('bad line: ' + line)
        pre, name, post = m.groups()
        member = name[1].lower() + name[2:]
        if name.startswith('s'):
            member = 's' + name[1:]
        members.append(f'{pre}{member}{post};')
        if not name.endswith('Storage'):
            macros.append(f'#define {name} (gSim->{member})')
    with open(os.path.join(outdir, 'sim_state_fields.h'), 'w') as f:
        f.write('// Generated by sim/tools/gen_state.py -- do not edit\n')
        f.write('\n'.join('    ' + m if not m.startswith('//') else m for m in members) + '\n')
    with open(os.path.join(outdir, 'sim_globals_gen.h'), 'w') as f:
        f.write('// Generated by sim/tools/gen_state.py -- do not edit\n')
        f.write('\n'.join(macros) + '\n')

if __name__ == '__main__':
    main()
