#!/usr/bin/env python3
"""Generate tests/scenarios/species_sweep.c: every species at level 50 with its four latest level-up
moves, attacking and being attacked by a fixed Snorlax for three turns. No sim-only checks; the point
is to cross-check every species' stats/ability/type handling against the real game."""
import os, re, sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
species = {}
for line in open(os.path.join(root, 'include/constants/species.h')):
    m = re.match(r'#define (SPECIES_\w+)\s+(\d+)', line)
    if m and not m.group(1).startswith('SPECIES_OLD_UNOWN') and m.group(1) not in ('SPECIES_NONE', 'SPECIES_EGG'):
        n = int(m.group(2))
        if n < 412 and n not in species:
            species[n] = m.group(1)
# level-up learnsets: map species -> list of (level, move)
ls = open(os.path.join(root, 'src/data/pokemon/level_up_learnsets.h')).read()
sets = {}
for m in re.finditer(r'static const u16 s(\w+)LevelUpLearnset\[\] = \{(.*?)\};', ls, re.S):
    moves = re.findall(r'LEVEL_UP_MOVE\(\s*(\d+),\s*(MOVE_\w+)\)', m.group(2))
    sets[m.group(1)] = [(int(l), mv) for l, mv in moves]
ptrs = open(os.path.join(root, 'src/data/pokemon/level_up_learnset_pointers.h')).read()
sp2set = dict(re.findall(r'\[(SPECIES_\w+)\]\s*=\s*s(\w+)LevelUpLearnset', ptrs))
out = ['// Generated by sim/tools/gen_species_scenarios.py -- do not edit', '#include "scenario.h"', '',
       'static const struct Scenario sScenarios[] =', '{']
count = 0
for n in sorted(species):
    name = species[n]
    if name not in sp2set:
        continue
    learn = [mv for l, mv in sets[sp2set[name]] if l <= 50]
    moves = []
    for mv in reversed(learn):
        if mv not in moves:
            moves.append(mv)
        if len(moves) == 4:
            break
    moves = list(reversed(moves))
    while len(moves) < 4:
        moves.append('MOVE_NONE')
    out.append('    { .name = "%s", .player = { MON(%s, 50, %s) }, .enemy = { MON_AB(SPECIES_SNORLAX, 50, MOVE_TACKLE, MOVE_SPLASH, MOVE_SPLASH, MOVE_SPLASH, 1) },'
               % (name[8:].lower(), name, ', '.join(moves)))
    out.append('      .actions = { T(0, 0), T(1, 0), T(2, 0), T(3, 0) }, .turns = 4 },')
    count += 1
out += ['};', '', 'SCENARIO_GROUP(species_sweep, sScenarios)', '']
open(sys.argv[1], 'w').write('\n'.join(out))
print(count, 'species scenarios')
