#!/usr/bin/env python3
"""Collect SCENARIO_GROUP(name, ...) declarations from tests/scenarios/*.c into gen/scenario_list.c."""
import glob, os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
names = []
for f in sorted(glob.glob(os.path.join(here, '..', 'tests', 'scenarios', '*.c'))):
    names += re.findall(r'SCENARIO_GROUP\((\w+)\s*,', open(f).read())
tmp = sys.argv[1] + '.tmp.%d' % os.getpid()
with open(tmp, 'w') as out:
    out.write('// Generated by sim/tools/gen_scenarios.py -- do not edit\n#include "scenario.h"\n')
    for n in names:
        out.write('extern const struct ScenarioGroup gScenarioGroup_%s;\n' % n)
    out.write('const struct ScenarioGroup *const gScenarioGroups[] = {\n')
    for n in names:
        out.write('    &gScenarioGroup_%s,\n' % n)
    out.write('};\nconst int gScenarioGroupCount = %d;\n' % len(names))
os.replace(tmp, sys.argv[1])
print(len(names), 'scenario groups')
